### ISSUE TITLE
order with same id is already present

### ISSUE THREAD

**Issue by iuzairjan** [cashfree/cashfree-whmcs#10]
Bug related to #9

<img width="1395" alt="Screenshot at Oct 26 13-33-48" src="https://user-images.githubusercontent.com/25842257/197969710-a7c04714-c16b-415b-a2c0-d4f84be59100.png">

**Comment by iuzairjan** [comment]
Update WHMCS Daily cron doesn't work. when invoices are stuck like that

**Comment by ankeshanand1** [comment]
Check Pull Request #8 . It resolves this issue by using `time()` function to create a different order id every time!

**Comment by prem-cashfree** [comment]
Hi @ankeshanand1 I have published a new release. Please find the latest update [here](https://github.com/cashfree/cashfree-whmcs/releases/tag/v2.0.0)

**Comment by iuzairjan** [comment]
oh wow @prem-cashfree finally decided to fix and rescue his mess, after a year lol

**Comment by blakstrox** [comment]
![screenshot-cp mxxxxt xiz-2023 05 04-13_01_56](https://user-images.githubusercontent.com/71962656/236138950-b470486b-4000-4055-a682-ccd7714afd86.png)

@prem-cashfree New issue after updating to v2.0.0. Can you please let me know what is this about?
