### ISSUE TITLE
Getting error "invalid body in request for x-idempotency-key"

### ISSUE THREAD

**Issue by blakstrox** [cashfree/cashfree-whmcs#12]
I am getting a new error after updating to v2.0.0 @prem-cashfree. This happens after I complete a successful payment and when the redirection from cashfree to WHMCS happens

![screenshot-cp mxxxxt xiz-2023 05 04-13_01_56](https://user-images.githubusercontent.com/71962656/236140032-c0df3784-8784-473d-ac64-c82160f14ec4.png)

I have updated to new version coz I was getting error as mentioned in the below issue.
[Issue10](https://github.com/cashfree/cashfree-whmcs/issues/10)

**Comment by prem-cashfree** [comment]
It's fix in updated codebase @blakstrox
