### ISSUE TITLE
Shows no payment due

### ISSUE THREAD

**Issue by cystec** [cashfree/cashfree-whmcs#4]
When a user cancels the payment.

The order status changes to "No invoice Due" however the invoice remains unpaid.

Screenshot attached.

<img width="1173" alt="Screenshot 2020-12-22 at 3 52 54 PM" src="https://user-images.githubusercontent.com/22011887/102878354-18e9d100-446e-11eb-9875-faa31423171e.png">

**Comment by cystec** [comment]
In gateway log, it doesn't show any debug data.

Only shows:


Invoice ID Not Found
--

**Comment by prem-cashfree** [comment]
Issue got fix in latest release. Please use latest [version](https://github.com/cashfree/cashfree-whmcs/releases/tag/1.0.1).

**Comment by cystec** [comment]
> Issue got fix in latest release. Please use latest [version](https://github.com/cashfree/cashfree-whmcs/releases/tag/1.0.1).

Another issue came up now!
