### ISSUE TITLE
Bug on cancelling payment

### ISSUE THREAD

**Issue by cystec** [cashfree/cashfree-whmcs#7]
Click pay now button from WHMCS, then it redirects you to cashfree page.

Now cancel the payment & cashfree will successfully redirect you to whmcs invoice and output will show: Payment failed etc. & Invoice unpaid.

Now attempt to Pay again.

**Cashfree will throw this error: ERROR: Order with same id is already present**

I believe this will also happen when user's payment gets failed instead of cancel.

**Comment by big89** [comment]
If Cashfree requires unique orderId in each payment request, then this error will occur as WHMCS passing same orderId every time we are initiating payment request for same invoice.

This can be get resolved by making orderId parameter unique in gateway file like concatenating timestamp or some random number.

**Comment by ankitsuryawanshi** [comment]
Has this issue been resolved or is it still there?

**Comment by iuzairjan** [comment]
Solve this issue, you ppl only ignore it.  I don't know why the hell I'm paying gateway charges when you cannot fix your tools

**Comment by prem-cashfree** [comment]
@iuzairjan we are working on it and publish a new release with all this fixes.

**Comment by prem-cashfree** [comment]
@iuzairjan and @cystec we have released a new updated. Can you use updated one for latest change.
